### ISSUE TITLE
Finalize design comps

### ISSUE THREAD

**Issue by blerchin** [blerchin/dma-20-mfa-show#10]
Generate high fidelity composites for the following page templates:
- Home page
- About page/curatorial statement
- Artist page (modular)

**Comment by dalena** [comment]
Final comps here
https://drive.google.com/drive/folders/1t0EqMwWyXHWNc7vNHoMbGIFMERWzE3hl?usp=sharing

**Comment by brysonian** [comment]
Great, not sure who will implement in the end, but can you list the fonts and sizes? Since it is all PNG we can't see that info. thanks!

**Comment by lmccart** [comment]
@dalena Possible to post illustrator files or whatever tool you're using?

**Comment by dalena** [comment]
I'm using Poppins for 1st lvl header and LetterGothicStd for body and secondary headers. Added them to fonts folder in the shared drive. FYI the fonts are still tentative. @beelaineo is deciding on the fonts. Re: illustrator files, I did it a hacky way and didn't make several canvases for the mockups this time. But I'll work on that tonight and add it to the drives. I'll ping you all when that's ready.

**Comment by dalena** [comment]
Just added the illustrator files to their respective folders: project-sub > desktop, project-sub > mobile, chat. The homepage and info I don't have AI files for but I can explain if it's not already clear from the screenshots in their folders.

**Comment by lmccart** [comment]
great, thank you!
