### ISSUE TITLE
Large top margin on Berfin's Page

### ISSUE THREAD

**Issue by hsab** [blerchin/dma-20-mfa-show#123]
![Screenshot_20200529_211245](https://user-images.githubusercontent.com/11205091/83319244-8c39a600-a1f1-11ea-9c24-7dca494c286a.png)

**Comment by blerchin** [comment]
this is a weird one. If you inspect the page you'll see that the iframe is actually being sized properly. When the video is playing, it fills the frame as expected. But the css vimeo uses to position their poster frame is a little wonky, and doesn't work in certain cases.

I think the best solution here would be to make our own poster frame that will cover the iframe, then hide and start the video when clicked. Similar to what I've done with the map on my page.

Edit: iframe is not actually being sized correctly. It seems like the ratio for this video may be set incorrectly with `padding-bottom: 133.33%` and `max-width: 72vh`.
