### ISSUE TITLE
Remove the image from Leming's page

### ISSUE THREAD

**Issue by lemingzhong** [blerchin/dma-20-mfa-show#127]
Hi~ I had so many friends who had trouble finding my video, so I wonder if I can remove the image from the top and just show my video and description there. I think it will make viewer easier to navigate. Thank you for the help!

**Comment by dalena** [comment]
Hi @lemingzhong I just saw this let me see if I can help

**Comment by dalena** [comment]
Hi @lemingzhong you should see the video at the top now. I'm closing this issue.
