### ISSUE TITLE
labels do not always appear when collapsed blobs are hovered

### ISSUE THREAD

**Issue by blerchin** [blerchin/dma-20-mfa-show#39]
This seems to apply only when the page has been visited via client-side routing. E.g: if I go directly to <https://kind-tesla-a088c1.netlify.app/ben-lerchin> it works. But if I go to the homepage and then click the Ben Lerchin blob, then hover over collapsed blobs it does not show up.

**Comment by blerchin** [comment]
figured out the problem, it's a super annoying closure issue. Because of where `calculateStyle` is defined it refers to the `collapsed` variable from when the component was first mounted. So it doesn't know when `collapsed` has  changed.

**Comment by hsab** [comment]
can we simply pass the current collapse value to `calculateStyle` as a func param?

**Comment by blerchin** [comment]
yes, but if you try it you'll see it's not that simple. because also `onArtistHovered` does not have access to the latest `collapsed`
I have an idea how to solve. Will make a PR in a couple mins.

**Comment by blerchin** [comment]
This covers the issue fairly well, though not the exact scenario here: https://dmitripavlutin.com/react-hooks-stale-closures/

**Comment by hsab** [comment]
#40 closes
