### ISSUE TITLE
custom styling and integration of code for dalena page

### ISSUE THREAD

**Issue by lmccart** [blerchin/dma-20-mfa-show#42]
I've taken a quick first pass, but there's more to be done here.

from @dalena:

aitImg1 is my cover image and would like it to blur on scroll. aitImg2 is fixed beneath the cover image. The first four text objects in my work description, I would like to be arranged around the button that leads to my actual project page "VIEW ACTS IN TRANSLATION". The button is sticky and centered vertically and horizontally on the page.

I would prefer to integrate my project files currently @ https://dalena.github.io/acts-in-translation/ directly into the site (not just an iframe). I would also like the button that the user clicks on "VIEW ACTS IN TRANSLATION" to activate the audiocontext in the browser instead of creating another splash screen to create that audiocontext user interaction again. I hope this makes sense. Thank you in advance! 

![aitMockupv1 - DALENA TRAN](https://user-images.githubusercontent.com/191056/82405809-c77ded00-9a19-11ea-9920-e02c59753398.png)

**Comment by dalena** [comment]
@lmccart thanks for putting most of this together! I'm gonna take on this issue right now and try to complete the styling/responsiveness. I will need help integrating my static site project files at a later date.
