### ISSUE TITLE
Automatic scroll to top on route change

### ISSUE THREAD

**Issue by hsab** [blerchin/dma-20-mfa-show#53]
Currently if an artist is viewed, and the user scrolled to middle/end of the page, upon clicking on another artist the scroll offset remains at the same spot. The correct behavior should be scrolling to the top of the page when routes change.

**Comment by brysonian** [comment]
I'm a bit swamped on the sr show site, but this is a classic. RR4's solution is here: https://reacttraining.com/react-router/web/guides/scroll-restoration I'll try to get to it later today.
