### ISSUE TITLE
Link domain to deployment from this repo

### ISSUE THREAD

**Issue by blerchin** [blerchin/dma-20-mfa-show#55]
How is the landing page on <near.rest> hosted? How do we make it a one-click process to make the site go live on friday?

Best way I can think of switch it to the netlify project that is connected to this repo so it will be a one-click switch to make this go live when we are ready. We could put the current landing page site on a branch and host that on the domain, then switch netlify to deploy `master` on Friday. 

@hsab how does that sound to you? I'm open to other ideas, just don't want to be messing with DNS at the last minute.

**Comment by hsab** [comment]
Right now I'm just using the custom domain for github pages and serving from [`dma20-paper-test/master`](https://github.com/hsab/dma20-paper-test)

[DNS settings ](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain) are pointing to github pages. I think netlify requires both adding dns records and reassigning the nameservers.

I created a new branch called [`temp-landing`](https://github.com/blerchin/dma-20-mfa-show/tree/temp-landing) to use until Friday. This is a clone of what we currently have. 

I think what you suggested sounds great. Let me know how I can help. You can also send me an invite on netlify as a team member on the project I think. We can hop on a call and set it up on both the registrar and netlify.

**Comment by blerchin** [comment]
Great, thanks! Let's hold off on this for the time being. I think we may want to switch back to Github Pages due to some issues with Netlify
- They make it really difficult to use Git LFS unless you use their proprietary version of it
- I am running out of build time on the free plan

A side benefit of the prerendering you've set up is that we actually can use GitHub pages now. The only issue before was that they don't have a way to run a SPA with multiple routes that should all resolve to one html file.
Travis CI is free for public repos, so we could setup build there and deploy to Pages.
Kind of annoying, but if it paves the way for large files and saves $$, probably worth the effort.

**Comment by brysonian** [comment]
My offer to host still stands too! Won't cost me anything.

I was thinking of some combo of https://medium.com/peerigon/how-to-continuously-deploy-a-cra-using-github-actions-and-zeit-f7bbd3b60da3 and https://github.com/marketplace/actions/scp-files

I haven't used actions but i'm eager to.

**Comment by hsab** [comment]
I'm personally a fan of GitHub pages. And yes with the pre-rendering we don't need to worry about routes anymore. I think their automatic compression, cdns, and all the behind the scene help with load time and performance. I'm not sure how lfs plays with pages though

**Comment by hsab** [comment]
Just checked. Lfs doesn't work pages

**Comment by blerchin** [comment]
@hsab yeah I guess it is a problem if we deploy files that are too big for git... to git. huh 🤔

**Comment by blerchin** [comment]
@brysonian if you're up for doing a bit of scripting it would be great to have this deploy to a regular ole server somewhere
The one netlify feature I will miss a lot if we ditch it is the PR builds. Wonder if we could throw together something that replicates that function though.

**Comment by blerchin** [comment]
Also possible to stay on Netlify while we are actively developing. I don't want to waste a lot of dev time on this project and it is looking increasingly like a yak shave. The increased build allowance runs about $45 so it's not super prohibitive.
I am personally about 50/50 on whether I actually need to host videos for my page. And if I end up needing it I could always just throw my video files on a server somewhere.

**Comment by blerchin** [comment]
Actually I just reread Netlify's email to me and we get another 500 build minutes for $7, which should get us through the next week. So let's not worry about the build time, I can eat that cost or maybe we can roll it into the show budget. But the LFS issues remain a concern.

**Comment by hsab** [comment]
I like some of the functionalities we get with netlify. I appreciate @brysonian's offer but I haven't had that good of an experience with shared/private hosting particularly during high traffic which will likely be the case on Friday. 

If your videos are <100 MB we can go ahead and use github pages. I think github pages is probably the high-yield-low-hanging solution. Doesn't require messing with scripts/automation and at its simplest all we need to do is rename our `build` dir to `docs` and make sure it's not ignored on push.

**Comment by hsab** [comment]
Ok found a nice workaround for gh-pages/netlify!!! The trick is to not use the repo, but upload the video as releases! File size limit increases to 2GB, there is not limit on how many files we can upload, repo remains manageable as large media are decoupled from it, and everything remains in the same place. Netlify and all the other stuff should work as expected. 

Embedding is as simple as setting the `src` to the release asset link. 

Did a successful test with a 460MB 60fps 4K video.
[Test Page](https://hsab.github.io/vid-thru-release/)
[Test Repo](https://github.com/hsab/vid-thru-release/releases)
Edit: colors are weird bc I ripped from utube and there's some hdr encoding going on.

**Comment by hsab** [comment]
I think with this hack we can just stick to netlify and use @blerchin's suggestion from https://github.com/blerchin/dma-20-mfa-show/issues/55#issue-623775670

**Comment by lmccart** [comment]
Hello, just peeping in here. I'm worried about using a hack, I think it runs the risk of GitHub shutting it down because it's not in line with their guidelines for gh-pages. Most likely they wouldn't catch it, but you never know. 

@blerchin I saw your comment in your PR thread about moving all videos off vimeo. I'm not sure this is worth the headache, especially if artists aren't requesting it. You could end up spending a lot of time converting video files, which becomes especially annoying if there are last minute changes to videos. At least vimeo would let them continue to update the video file without it touching your end. And some of the artists may even want the viewing stats and share features you get with vimeo. If you or Dalena want to embed your own video files that's different because you can be directly responsible for getting that working, and it's just a few files then.

**Comment by brysonian** [comment]
I'm not sure performance is a valid concern, but that's fine.

Either way, gh-pages isn't made for serving large media. Why not move the videos to something like https://cloudinary.com/ which will give you a CDN, better performance, and still be free. I had hesitated to recommend it because i didn't want to involve another service, but it is actually purpose built for this. 

Another option is S3, which while not free is pretty close to it, and would still be more performant and not require hacks.

**Comment by blerchin** [comment]
yeah I was hoping the LFS thing would be a quick solution to a problem I was having, and then facilitate archiving down the road. I wasn't expecting we would use it for everyone's videos right away. Sorry if I scared anyone with this thread!
I agree the path of least resistance (keep using Netlify) is probably best for the moment.

I think using Cloudinary or S3 is probably a good solve for the moment. Or in my case since the video I want to loop is <100MB I can hold my nose and commit it. I hate to add external dependencies for the project, but I still prefer that to hacking around with releases.

**Comment by hsab** [comment]
All valid points. I don't think there's any issue with committing. From what I know only you and Dalena have self hosted videos, and hers is on a different repo. So we should be good. 

@blerchin  When you get a chance can you please revert the netlify changes so we can get PR builds up and running again?

**Comment by blerchin** [comment]
@hsab I fixed the netlify stuff this morning. Should be good to go again :)
