### ISSUE TITLE
FOUT issue with NEARREST NEIGHBOR

### ISSUE THREAD

**Issue by blerchin** [blerchin/dma-20-mfa-show#65]
When I initially load the page, I see the show title in system font and wider than the actual title. About half a second later it reflows to the correct appearance.

We should delay rendering this until webfonts are loaded. This can happen by using `<link>` tags for our fonts instead of CSS imports, or by waiting for the load event in Javascript.

**Comment by hsab** [comment]
The sizing issue comes from the static builder from what I can recall. During crawling it will harcode the width and height. I have it set so that on initial load it sets the w/h to the window size. We could hide it until the attributes are set and then display.
+1 for fonts
