### ISSUE TITLE
Add Home/Info Nav to Homepage

### ISSUE THREAD

**Issue by dalena** [blerchin/dma-20-mfa-show#68]
Adding the nav component to the homepage would be a good idea so people have a chance to read curatorial statement before jumping into the projects. 

Also, regarding the initial mockups there were concerns to have a nav bar of artist names on homepage to make it easier for people to navigate to projects that they were already looking for or also so they don't have to use the blob feature. Is this still something we should attempt? 

![desktop](https://user-images.githubusercontent.com/4734846/82846145-4f417c80-9e9c-11ea-83ff-a9f67c233d10.png)

**Comment by blerchin** [comment]
Made a PR with the simplest possible layout option. I think it works alright, but open to other ideas.

https://github.com/blerchin/dma-20-mfa-show/pull/74

For the artist names on the side, I think they are redundant. I've found the rollover labels on the blobs when they are in the collapsed position to be totally adequate when I want to go to a specific artist.

**Comment by dalena** [comment]
Sounds good to me, closing this issue!
