### ISSUE TITLE
project cover obscured on mobile

### ISSUE THREAD

**Issue by BerfinA** [blerchin/dma-20-mfa-show#82]
On my site there is a video that plays which is the first image. On the mobile it just skips it so you dont get to see the video at all.

**Comment by lmccart** [comment]
good catch! i'll work on this

**Comment by lmccart** [comment]
<img width="413" alt="Screen Shot 2020-05-27 at 2 30 17 PM" src="https://user-images.githubusercontent.com/191056/83074275-be4adc80-a026-11ea-9bf6-f2acbb70bc19.png">
<img width="412" alt="Screen Shot 2020-05-27 at 2 31 04 PM" src="https://user-images.githubusercontent.com/191056/83074287-c1de6380-a026-11ea-83db-d85a8f7cbbc8.png">

On mobile, the cover image/video is centered on the page, but it's often obscured by the project heading, especially if there's a lot of text or it's a vertical video. I'm wondering if we should just lose the project cover fadeback on mobile, and put everything in a single flow for this view. Thoughts? @dalena @hsab @blerchin

**Comment by dalena** [comment]
I think that's a good call @lmccart
