### ISSUE TITLE
Phone interaction test

### ISSUE THREAD

**Issue by BerfinA** [blerchin/dma-20-mfa-show#96]
On my artist page( on the phone) the video is cropped and also there is no option to enlarge the video or a button that appears to indicate to press play. On other pages the videos seem to work ok.

**Comment by lmccart** [comment]
@BerfinA the lack of buttons is due to the autoplay functionality. i'm going to turn off autoplay so it works properly on mobile.

**Comment by BerfinA** [comment]
Thanks  @lmccart , now the titles are on the video like it was before.
